version: '3.8'

services:
  auth-service:
    build:
      context: ./authentication_service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - CORS_ORIGIN=*
    volumes:
      - ./authentication_service:/usr/src/app:rw
      - /authentication_service/src/app/node_modules
    networks:
      - default

  core-service:
    build:
      context: ./core_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVER=http://localhost:3001
    volumes:
      - ./core_service:/usr/src/app
      - /core_service/src/app/node_modules
    command: npm run dev
    restart: unless-stopped
    depends_on:
      - auth-service

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_AUTH_API_URL=http://localhost:3001
      - VITE_CORE_API_URL=http://localhost:3000
    volumes:
      - ./client:/usr/src/app
      - /client/src/app/node_modules
    command: npm run dev
    restart: unless-stopped
    depends_on:
      - core-service
    networks:
      - default

networks:
  default:
    driver: bridge 
