version: '3.8'

services:
  auth-service:
    build:
      context: ./authentication_service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./authentication_service:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  core-service:
    build:
      context: ./core_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./core_service:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

networks:
  default:
    driver: bridge 